### ISSUE TITLE
Type error in scheduler module

### ISSUE THREAD

**Issue by onyxnz** [backdrop-contrib/scheduler#21] opened 2023-07-10 22:56 UTC
Upon Preview of a node in creation:
TypeError: trim(): Argument #1 ($string) must be of type string, array given in trim() (line 251 of /var/www/clients/client1/web1/web/modules/scheduler/scheduler.module).

I couldn't see how it was getting called, but guess it must be a hook somewhere.
My fix: force the array to string, as done elsewhere in that module, like so:
`function _scheduler_strtotime($str) {
  $config = config('scheduler.settings');
  if(is_array($str)){// with Preview of a node there is an array sent here, containing date and time
    $str=$str['date'].' '.$str['time'];
  }  
  if ($str && trim($str) != "") {`

**Comment by laryn** [comment] 2024-10-24 22:34
@onyxnz Can you test the dev code and see if you can reproduce this? It may be fixed -- I can't reproduce.

**Comment by onyxnz** [comment] 2024-10-25 05:03
Dev code? I can't see any...

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by laryn** [comment] 2024-10-25 05:28
@onyxnz For example by pulling the latest code from this repo, or downloading the zip file here: 
![CleanShot 2024-10-25 at 00 27 57@2x](https://github.com/user-attachments/assets/35fcb272-b7c1-4726-906c-71fc1d36480d)

**Comment by laryn** [comment] 2024-10-28 16:08
@onyxnz I've made a new beta release so testing can just be done on the latest release at this point. Let me know if you can reproduce this error, or if it seems to be fixed in the latest.

**Comment by laryn** [comment] 2024-11-01 15:29
Please reopen if this is still an issue going forward.

**Closed as completed by laryn** 2024-11-01 15:29 UTC
